using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using AvaloniaVS.Shared.Services;
using dnlib.DotNet;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;

namespace AvaloniaVS.Shared.Navigation
{
    internal static class DnlibStubGenerator
    {
        private const string Nl = "\r\n"; // explicit everywhere - never rely on Environment.NewLine
                                          // or a literal string containing "\n", to avoid mixed EOL warnings

        public static string GenerateStub(string fullyQualifiedTypeName, IReadOnlyList<string> assemblyPaths, XmlDocCache docCache)
        {
            if (assemblyPaths == null || assemblyPaths.Count == 0)
                return null;

            var asmResolver = new AssemblyResolver { EnableTypeDefCache = false, UseGAC = false };
            var modCtx = new ModuleContext(asmResolver, new Resolver(asmResolver) { ProjectWinMDRefs = false });
            asmResolver.DefaultModuleContext = modCtx;

            foreach (var path in assemblyPaths)
                asmResolver.PreSearchPaths.Add(path);

            TypeDef typeDef = null;

            foreach (var path in assemblyPaths)
            {
                try
                {
                    var asm = AssemblyDef.Load(File.ReadAllBytes(path),
                        new ModuleCreationOptions(modCtx) { TryToLoadPdbFromDisk = false });
                    asmResolver.AddToCache(asm);

                    typeDef ??= asm.ManifestModule.Find(fullyQualifiedTypeName, isReflectionName: true);
                }
                catch
                {
                    // best-effort - a single unreadable/unresolvable assembly shouldn't
                    // block finding the type in one of the others
                }
            }

            return typeDef == null ? null : Emit(typeDef, docCache);
        }

        private static string Emit(TypeDef type, XmlDocCache docCache)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>").Append(Nl);
            sb.Append("// Generated by AvaloniaVS from referenced assembly metadata (dnlib).").Append(Nl);
            sb.Append("// Signatures only - not the original source.").Append(Nl);
            sb.Append("// </auto-generated>").Append(Nl).Append(Nl);

            var ns = type.Namespace.String;
            if (!string.IsNullOrEmpty(ns))
                sb.Append("namespace ").Append(ns).Append(Nl).Append('{').Append(Nl);

            AppendSummary(sb, docCache?.TryGetTypeSummary(type.FullName), "    ");

            sb.Append("    public ");
            sb.Append(type.IsSealed ? "sealed " : "");
            sb.Append(type.IsInterface ? "interface " : type.IsAbstract ? "abstract class " : "class ");
            sb.Append(type.Name);

            var bases = new List<string>();
            if (type.BaseType != null && type.BaseType.FullName != "System.Object")
                bases.Add(FormatTypeName(type.BaseType));
            bases.AddRange(type.Interfaces.Select(i => FormatTypeName(i.Interface)));
            if (bases.Count > 0)
                sb.Append(" : ").Append(string.Join(", ", bases));

            sb.Append(Nl).Append("    {").Append(Nl);

            // fields - public/protected instance and const/static, skip compiler-generated backing fields
            foreach (var field in type.Fields.Where(f => (f.IsPublic || f.IsFamily) && !f.Name.String.Contains("k__BackingField")))
            {
                AppendSummary(sb, docCache?.TryGetFieldSummary(type.FullName, field.Name), "        ");
                sb.Append("        public ");
                if (field.IsLiteral)
                    sb.Append("const ");
                else if (field.IsStatic)
                    sb.Append("static ");
                if (field.IsInitOnly)
                    sb.Append("readonly ");
                sb.Append(FormatTypeName(field.FieldType)).Append(' ').Append(field.Name).Append(';').Append(Nl);
            }

            // constructors
            foreach (var ctor in type.Methods.Where(m => m.IsConstructor && (m.IsPublic || m.IsFamily)))
            {
                var parameters = FormatParameters(ctor);
                sb.Append("        public ").Append(type.Name).Append('(').Append(parameters).Append(')').Append(';').Append(Nl);
            }

            // properties (including indexers, which carry parameters on the getter/setter)
            foreach (var prop in type.Properties.Where(IsPubliclyVisible))
            {
                AppendSummary(sb, docCache?.TryGetPropertySummary(type.FullName, prop.Name), "        ");
                var indexParams = (prop.GetMethod ?? prop.SetMethod)?.Parameters
                    .Where(p => !p.IsHiddenThisParameter && !p.IsReturnTypeParameter).ToList();

                sb.Append("        public ").Append(FormatTypeName(prop.PropertySig.RetType)).Append(' ');
                if (indexParams is { Count: > 0 })
                    sb.Append("this[").Append(string.Join(", ", indexParams.Select(p => $"{FormatTypeName(p.Type)} {p.Name}"))).Append(']');
                else
                    sb.Append(prop.Name);

                sb.Append(" { ");
                if (prop.GetMethod?.IsPublic == true)
                    sb.Append("get; ");
                if (prop.SetMethod?.IsPublic == true)
                    sb.Append("set; ");
                sb.Append('}').Append(Nl);
            }

            // events
            foreach (var evt in type.Events.Where(e => e.AddMethod?.IsPublic == true))
            {
                AppendSummary(sb, docCache?.TryGetEventSummary(type.FullName, evt.Name), "        ");
                sb.Append("        public event ").Append(FormatTypeName(evt.EventType)).Append(' ').Append(evt.Name).Append(';').Append(Nl);
            }

            // methods - own declared, public, not a ctor, not a property/event accessor (get_/set_/add_/remove_)
            foreach (var method in type.Methods.Where(m =>
                         m.IsPublic && !m.IsConstructor && !m.IsSpecialName))
            {
                var parameters = FormatParameters(method);
                sb.Append("        public ").Append(method.IsStatic ? "static " : "")
                  .Append(FormatTypeName(method.ReturnType)).Append(' ').Append(method.Name)
                  .Append('(').Append(parameters).Append(')').Append(';').Append(Nl);
            }

            // nested types - listed, not expanded (avoids unbounded recursion into nested classes)
            foreach (var nested in type.NestedTypes.Where(t => t.IsNestedPublic))
                sb.Append("        public class ").Append(nested.Name).Append(" { /* nested type - navigate separately */ }").Append(Nl);

            sb.Append("    }").Append(Nl);
            if (!string.IsNullOrEmpty(ns))
                sb.Append('}').Append(Nl);

            return sb.ToString();
        }

        private static bool IsPubliclyVisible(PropertyDef prop) =>
            prop.GetMethod?.IsPublic == true || prop.SetMethod?.IsPublic == true;

        private static bool IsPubliclyVisibleMethod(MethodDef method) =>
            method.IsPublic && !method.IsSpecialName && !method.IsConstructor && !method.IsStatic == method.IsStatic
                && method.DeclaringType.BaseType?.FullName != "System.Object";

        private static void AppendSummary(StringBuilder sb, string summary, string indent)
        {
            if (string.IsNullOrEmpty(summary))
                return;

            sb.Append(indent).Append("/// <summary>").Append(Nl);
            sb.Append(indent).Append("/// ").Append(summary).Append(Nl);
            sb.Append(indent).Append("/// </summary>").Append(Nl);
        }

        private static string FormatParameters(MethodDef method) =>
    string.Join(", ", method.Parameters
        .Where(p => !p.IsHiddenThisParameter && !p.IsReturnTypeParameter)
        .Select(p => $"{FormatTypeName(p.Type)} {p.Name}"));

        private static string FormatTypeName(ITypeDefOrRef type) => FormatTypeName(type.ToTypeSig());

        private static string FormatTypeName(TypeSig sig)
        {
            if (sig == null)
                return "object";

            switch (sig)
            {
                case GenericInstSig gis:
                    var args = string.Join(", ", gis.GenericArguments.Select(FormatTypeName));
                    var baseName = gis.GenericType.TypeDefOrRef.Name.String;
                    var tickIndex = baseName.IndexOf('`');
                    if (tickIndex > 0)
                        baseName = baseName[..tickIndex];
                    return $"{baseName}<{args}>";

                case SZArraySig arr:
                    return FormatTypeName(arr.Next) + "[]";

                default:
                    return sig.TypeName switch
                    {
                        "Int32" => "int",
                        "Int64" => "long",
                        "Boolean" => "bool",
                        "String" => "string",
                        "Double" => "double",
                        "Single" => "float",
                        "Object" => "object",
                        "Void" => "void",
                        _ => sig.TypeName
                    };
            }
        }

        public static bool NavigateToGeneratedStub(IServiceProvider serviceProvider, string stub, string fullyQualifiedTypeName)
        {
            ThreadHelper.ThrowIfNotOnUIThread();

            var typeName = fullyQualifiedTypeName[(fullyQualifiedTypeName.LastIndexOf('.') + 1)..];

            var tempDir = Path.Combine(Path.GetTempPath(), "AvaloniaVS", "MetadataAsSource");
            Directory.CreateDirectory(tempDir);
            var filePath = Path.Combine(tempDir, $"{typeName}.cs");

            if (!File.Exists(filePath))
                File.WriteAllText(filePath, stub, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            int hr = VsShellUtilities.TryOpenDocument(
                serviceProvider, filePath, VSConstants.LOGVIEWID.TextView_guid,
                out _, out _, out var frame);

            if (ErrorHandler.Failed(hr) || frame == null)
                return false;

            frame.Show();
            return true;
        }
    }

}
