using System;
using System.IO;
using System.Text;
using Avalonia.Ide.CompletionEngine;
using AvaloniaVS.Shared.Services;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;

namespace AvaloniaVS.Shared.Navigation
{
    internal static class MetadataStubGenerator
    {
        public static string GenerateStub(MetadataType type, XmlDocCache docCache)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated by AvaloniaVS from referenced assembly metadata.");
            sb.AppendLine("// It shows only public API signatures - not the original source.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            var lastDot = type.FullName.LastIndexOf('.');
            var ns = lastDot > 0 ? type.FullName[..lastDot] : null;
            var name = lastDot > 0 ? type.FullName[(lastDot + 1)..] : type.FullName;

            if (ns != null)
                sb.AppendLine($"namespace {ns}\n{{");

            var summary = docCache?.TryGetTypeSummary(type.FullName);
            if (!string.IsNullOrEmpty(summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {summary}");
                sb.AppendLine("    /// </summary>");
            }

            sb.AppendLine($"    public class {name}");
            sb.AppendLine("    {");

            foreach (var prop in type.Properties)
            {
                var propSummary = docCache?.TryGetTypeSummary($"{type.FullName}.{prop.Name}");
                if (!string.IsNullOrEmpty(propSummary))
                    sb.AppendLine($"        /// <summary>{propSummary}</summary>");

                sb.AppendLine($"        public {prop.Type?.FullName ?? "object"} {prop.Name} {{ get; set; }}");
            }

            sb.AppendLine("    }");
            if (ns != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        public static bool NavigateToGeneratedStub(IServiceProvider serviceProvider, MetadataType type, XmlDocCache docCache)
        {
            ThreadHelper.ThrowIfNotOnUIThread();

            var tempDir = Path.Combine(Path.GetTempPath(), "AvaloniaVS", "MetadataAsSource");
            Directory.CreateDirectory(tempDir);
            var filePath = Path.Combine(tempDir, $"{type.Name}.cs");

            File.WriteAllText(filePath, MetadataStubGenerator.GenerateStub(type, docCache));

            int hr = VsShellUtilities.TryOpenDocument(
                serviceProvider, filePath, VSConstants.LOGVIEWID.TextView_guid,
                out _, out _, out var frame);

            if (ErrorHandler.Failed(hr) || frame == null)
                return false;

            frame.Show();
            return true;
        }
    }
}
